import { chromium } from "playwright";
const errors = [];
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 1280, height: 900 } });
p.on("console", (m) => m.type() === "error" && errors.push(m.text()));
p.on("pageerror", (e) => errors.push(String(e)));
await p.goto("http://127.0.0.1:8899/ar/privacy-policy", { waitUntil: "networkidle" });
const t = await p.locator("article").innerText();
console.log("اتجاه       :", await p.evaluate(() => document.documentElement.dir));
console.log("عنوان الهيرو:", await p.locator("h1").first().innerText());
console.log("عناوين فرعية:", await p.locator("article h2").count());
console.log("نقاط        :", await p.locator("article li").count());
console.log("تأكيد <strong>:", await p.locator("article strong").count(), "→", await p.locator("article strong").first().innerText());
console.log("نجوم ظاهرة  :", t.includes("**") ? "❌ لسه فيه **" : "✅ اتحوّلت");
console.log("آخر تحديث   :", t.includes("آخر تحديث") ? "✅" : "❌");
console.log("طفح أفقي    :", await p.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 1));
await p.setViewportSize({ width: 390, height: 844 });
await p.waitForTimeout(300);
console.log("طفح موبايل  :", await p.evaluate(() => document.documentElement.scrollWidth > document.documentElement.clientWidth + 1));
console.log("أخطاء       :", errors.length, errors.slice(0, 3));
await p.setViewportSize({ width: 1280, height: 900 });
await p.screenshot({ path: process.env.SHOT, fullPage: false });
await b.close();
